apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: task1
      taskRef:
        name: print-hello-task1
    - name: task2
      taskRef:
        name: print-hello-task2
      runAfter:
        - task1

