apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-hello-task2
spec:
  steps:
    - name: print-hello2
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        echo "Hello from Task 2"
